### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by ironoa**
https://github.com/w3f/infrastructure/issues/511

### CODE REVIEW

**Comment by ironoa** [comment]
@lamafab Regarding the naming convention, is this application generating something ( i.e. submitting an extrinsic, generating a transaction, etc. ) ? Or else is watching the on-chain data => watcher-claimed-payouts or something similar 
What do you think ?

**Review by lamafab — APPROVED** [review]

**Comment by lamafab** [comment]
@ironoa It just prints to stdout. This should be picked up by Grafana. Nothing more complicated than that :)

**Comment by ironoa** [comment]
> @ironoa It just prints to stdout. This should be picked up by Grafana. Nothing more complicated than that :)

Indeed, shall we rename the project watcher-claimed-payouts or 1k-watcher-claimed-payouts, or something similar ? to make it live close to the other watcher projects we have ? Or you think that the "claim-generator" describe it better ?

**Comment by lamafab** [comment]
Yes, will rename this to "1k-watcher-claimed-payouts".

**Pull request merged**
